-- Usando il database sakila, scrivere le query (istruzioni SQL) che soddisfano le seguenti richieste:
-- 1. Produrre l'elenco dei film (title, rating e rental_duration) ordinato per rental_duration decrescente.
-- 2. Produrre l'elenco dei pagamenti (amount, payment_date, customer_id) del mese di giugno 2005 con importo superiore a 3,00.
-- 3. Produrre l'elenco degli attori (last_name, first_name) per i quali la lunghezza del nome è maggiore di quella del cognome.
-- 4. Determinare il numero di film con rating ‘PG-13’ (PG-13: Parents Strongly Cautioned, Some Material May Be Inappropriate for Children Under 13).
-- 5. Elencare il numero di film usciti (release_year) in ciascun anno, ma solo per gli anni in cui sono usciti almeno 10 film.
-- 6. Produrre un elenco dei DVD (inventory_id, film.title, replacement_cost, payment) per il cui noleggio è stata pagata una somma maggiore del replacement_cost.
-- 7. Elenco dei noleggi (film.title, rental_date, return_date) effettuati dal cliente 'SUSAN WILSON'.
-- 8. Elenco dei DVD (inventory_id, n_clienti) noleggiati da almeno 5 clienti diversi.
-- 9. Elenco degli film (title) in cui hanno recitato almeno cinque attori.
-- 10. Elenco dei DVD (inventory_id) per i quali risultano noleggi contemporanei (cioè per i quali risultano almeno due noleggi temporalmente sovrapposti).

-- Istruzioni di consegna
-- Consegnare un file di testo CognomeNome20241007.sql con le query indicate, preferibilmente basato sul modello fornito.
-- NON è consentito utilizzare nelle query le view già esistenti nel database.
-- NON è consentito usare più di una query per ottenere il risultato finale.
-- L'unica possibilità è quella di creare query annidate oppure opportune view per semplificare quelle troppo complesse/prolisse.
